# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d91b492b126838666a7dc050b673aa1b1634610d04ac1c5b1d2f8279b62a51f609d3bddbc04653432075b4582f2402af80334bed4dec6e538a58055ba3c8333a

test:
  secret_key_base: 6baaa41d2888fde7d45705ee06c2a31651da9ba8a304c4c4f20f5ae2766d286c07387ebc8eb9bebe49eb170475a04dbb8dc427ed942bc5405cc0879bc1dbbd1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
